// Fixed event inventory: keep in sync with Core TELEMETRY.md and module registrations.
export const telemetryFeatureEvents: Record<string, string[]> = {
	'morelord-core': [],
	'morelord-journeys': ['dashboard.opened', 'journey.created', 'journey.arrived', 'phase.changed'],
	'morelord-downtime': [
		'dashboard.opened',
		'training.opened',
		'sourcing.opened',
		'research.opened',
		'project.create.attempted',
		'project.create.returned',
		'project.create.failed',
		'project.collect.attempted',
		'project.collect.returned',
		'project.collect.failed',
		'project.cancel.attempted',
		'project.cancel.returned',
		'project.cancel.failed',
		'session.create.attempted',
		'session.create.returned',
		'session.create.failed',
		'session.start.attempted',
		'session.start.returned',
		'session.start.failed',
		'session.finalize.attempted',
		'session.finalize.returned',
		'session.finalize.failed',
		'time.allocate.attempted',
		'time.allocate.returned',
		'time.allocate.failed'
	],
	'morelord-craftworks': [
		'dashboard.opened',
		'recipes.opened',
		'crafting.opened',
		'harvest.opened',
		'gather.opened',
		'loot.opened',
		'hoard.opened',
		'delerium.opened',
		'potions.opened',
		'materials.opened',
		'crafting.start.attempted',
		'crafting.start.returned',
		'crafting.start.failed',
		'crafting.check.attempted',
		'crafting.check.returned',
		'crafting.check.failed',
		'crafting.complete.attempted',
		'crafting.complete.returned',
		'crafting.complete.failed',
		'harvest.start.attempted',
		'harvest.start.returned',
		'harvest.start.failed',
		'harvest.claim.attempted',
		'harvest.claim.returned',
		'harvest.claim.failed',
		'loot.roll.attempted',
		'loot.roll.returned',
		'loot.roll.failed',
		'loot.award.attempted',
		'loot.award.returned',
		'loot.award.failed',
		'hoard.roll.attempted',
		'hoard.roll.returned',
		'hoard.roll.failed',
		'hoard.award.attempted',
		'hoard.award.returned',
		'hoard.award.failed'
	],
	'morelord-marketplace': [
		'marketplace.opened',
		'shops.opened',
		'shop.checkout.attempted',
		'shop.checkout.returned',
		'shop.checkout.failed',
		'catalog.buy-cart.attempted',
		'catalog.buy-cart.returned',
		'catalog.buy-cart.failed',
		'catalog.buy-item.attempted',
		'catalog.buy-item.returned',
		'catalog.buy-item.failed',
		'sell.cart.attempted',
		'sell.cart.returned',
		'sell.cart.failed',
		'sell.item.attempted',
		'sell.item.returned',
		'sell.item.failed'
	],
	'morelord-encounters': ['builder.opened', 'custom.opened', 'generated.opened', 'roster.opened'],
	'morelord-character-export': ['export.attempted', 'export.completed', 'export.failed']
};
