<svelte:head>
	<title>Morelord Core Documentation | Morelord Gaming</title>
	<meta name="description" content="Connect Foundry VTT to a Morelord Gaming account with Morelord Core." />
</svelte:head>

<section class="page-hero tools-hero compact-hero"><div class="shell"><div class="eyebrow">Product guide</div><h1>Morelord Core</h1><p class="lead">Connect your Foundry world to your Morelord account and provide shared membership access to Morelord Tools modules.</p></div></section>
<section class="section brand-panel-section"><div class="shell prose-content">
	<article class="card docs-card"><h2>Install and enable</h2><p>Manifest URL: <code>https://raw.githubusercontent.com/tmoreland72/morelord-core/main/module.json</code></p><ol><li>In Foundry Setup, open <strong>Add-on Modules → Install Module</strong> and paste the manifest URL.</li><li>Enable it in <strong>Manage Modules</strong>.</li><li>Enable any Morelord product modules that depend on Core.</li><li>Reload the world when Foundry requests it.</li></ol></article>
	<article class="card docs-card"><h2>Connect your account</h2><ol><li>Open <strong>Game Settings → Configure Settings → Module Settings</strong>.</li><li>Find <strong>Morelord Core</strong> and choose <strong>Connect or Manage Account</strong>.</li><li>Choose <strong>Connect account</strong> to generate a temporary code.</li><li>Open the displayed Morelord Gaming link, sign in and approve the connection.</li><li>Return to Foundry. Core completes the connection automatically.</li></ol><p>Only a Game Master should connect or disconnect the world.</p></article>
	<article class="card docs-card"><h2>Membership and access</h2><p>Core retrieves the membership and product features available to the connected account. Premium and Champion features are then unlocked inside supported modules. Standard module functionality remains available without a paid membership.</p><p>Use <strong>Refresh Access</strong> after changing membership or when newly assigned features do not appear immediately.</p></article>
	<article class="card docs-card"><h2>Offline use</h2><p>Core caches recently validated access so temporary website or internet interruptions do not immediately interrupt a game. Reconnect and refresh access when the cache expires.</p></article>
	<article class="card docs-card"><h2>Troubleshooting</h2><ul><li>Confirm the world has internet access to <code>morelordgaming.com</code>.</li><li>Confirm Morelord Core is enabled before dependent modules.</li><li>Refresh access after upgrading or downgrading membership.</li><li>Disconnect and reconnect if the linked account is incorrect.</li><li>Ask the Game Master to perform account-management actions.</li></ul></article>
</div></section>
