<svelte:head><title>Drakkenheim Harvesting Documentation | Morelord Gaming</title><meta name="description" content="Run Drakkenheim harvesting sessions in Foundry VTT with Morelord Drakkenheim Harvesting." /></svelte:head>
<section class="page-hero tools-hero compact-hero"><div class="shell"><div class="eyebrow">Product guide</div><h1>Morelord Drakkenheim Harvesting</h1><p class="lead">Guide the party through a shared harvesting attempt and distribute the finalized monster components.</p></div></section>
<section class="section brand-panel-section"><div class="shell prose-content">
	<article class="card docs-card"><h2>Requirements</h2><p>The module supports harvesting content from compatible Drakkenheim sources. <strong>Monsters of Drakkenheim</strong> is a paid Foundry package. The supported Antics &amp; Rolls harvesting content is free as of the current release.</p></article>
	<article class="card docs-card"><h2>Start a harvesting session</h2><ol><li>Select or open the defeated creature.</li><li>Launch the harvesting workflow from the provided actor control or Game Master macro.</li><li>Select the available components and participants.</li><li>Open the session for players.</li></ol></article>
	<article class="card docs-card"><h2>Player participation</h2><p>Players use the shared harvesting window to make the requested selections or rolls. Keep the window open until the Game Master has reviewed the results.</p></article>
	<article class="card docs-card"><h2>Finalize</h2><p>The Game Master chooses <strong>Finalize</strong> after all results are ready. Finalization completes the session, closes participant windows and sends completion notifications.</p></article>
	<article class="card docs-card"><h2>Missing harvesting data</h2><p>Some actors reference their harvesting information through embedded journal content rather than storing it directly in the biography. Ensure the required source modules and compendiums are enabled and accessible in the world.</p></article>
</div></section>
