<svelte:head><title>Morelord Marketplace Documentation | Morelord Gaming</title><meta name="description" content="Set up buying, selling and GM approvals with Morelord Marketplace for Foundry VTT." /></svelte:head>
<section class="page-hero tools-hero compact-hero"><div class="shell"><div class="eyebrow">Product guide</div><h1>Morelord Marketplace</h1><p class="lead">Give players a clear interface for buying from merchants and selling character inventory.</p></div></section>
<section class="section brand-panel-section"><div class="shell prose-content">
	<article class="card docs-card"><h2>Install and enable</h2><ol><li>Install and enable <strong>Morelord Core</strong>.</li><li>Install and enable <strong>Morelord Marketplace</strong>.</li><li>Reload the world.</li><li>Open Marketplace configuration as a Game Master.</li></ol></article>
	<article class="card docs-card"><h2>Select the transaction character</h2><p>For players, Marketplace first uses the actor represented by the currently selected token. When no valid token is selected, it falls back to the character assigned in the user configuration. Verify the selected token before completing a transaction.</p></article>
	<article class="card docs-card"><h2>Configure buying and selling</h2><p>The Game Master can independently allow character purchases and character sales. Configure the merchant, pricing behavior and available transaction types for the world.</p></article>
	<article class="card docs-card"><h2>GM approvals</h2><p>Tools Premium and Champion members can require approval for player purchases, sales or both. Each submitted transaction creates its own pending approval card. A Game Master approves or denies transactions individually.</p><p>Transactions performed directly by a Game Master bypass approval and are marked accordingly.</p></article>
	<article class="card docs-card"><h2>When membership changes</h2><p>Approval options become unavailable when paid access expires, but saved settings and transaction records are retained. Standard buying and selling continue to work. Reconnect or refresh Morelord Core after restoring membership.</p></article>
</div></section>
