<svelte:head><title>Installation Analytics | Morelord Admin Docs</title><meta name="robots" content="noindex,nofollow" /></svelte:head>
<section class="page-hero compact-hero"><div class="shell"><div class="eyebrow">Admin docs</div><h1>Installation analytics</h1><p class="lead">Understand connected Foundry worlds, active accounts and membership conversion.</p></div></section>
<section class="section brand-panel-section"><div class="shell"><article class="prose-card card">
<h2>What counts as an installation?</h2><p>A registered installation is a Foundry world that has connected Morelord Core to a Morelord Gaming account. GitHub release downloads are intentionally not treated as installations because updates, reinstalls and automated downloads can inflate those numbers.</p>
<h2>What counts as active?</h2><p>An installation is active when it has successfully checked Morelord access recently. The dashboard reports 7-day, 30-day and 90-day activity. The 30-day window is used for the main membership and conversion metrics.</p>
<h2>Accounts versus worlds</h2><p>One account can connect multiple Foundry worlds. <strong>Active installations</strong> counts worlds, while <strong>Active accounts</strong> deduplicates those worlds by Morelord account. Paid conversion uses unique active accounts so multiple worlds do not inflate the percentage.</p>
<h2>Membership mix</h2><p>The dashboard classifies each active account from the current synchronized subscription as Standard, Premium or Champion. A canceled or expired paid subscription is counted as Standard after its paid access ends.</p>
<h2>Product activity</h2><p>Whenever a Morelord module requests product entitlements through Core, the website records that the connected installation used that Morelord product. This provides product adoption counts without collecting campaign content.</p>
<h2>Version statistics</h2><p>Morelord Core can send only the installed Core and Foundry versions during an access check. Game Masters can disable this with <strong>Share Anonymous Usage Statistics</strong>. Disabling version statistics does not disable access checks, so the installation can still count as active.</p>
<h2>Privacy</h2><p>The installation analytics feature does not add campaign names, world names, player names, actors, items, chat messages or gameplay content to the anonymous version report. Account and installation records already required for account linking remain private administrative data.</p>
</article></div></section>
